### ISSUE TITLE
Question about drag-drop indication

### ISSUE THREAD

**Issue by GFPdu** [kommitters/editorjs-drag-drop#16]
Hey guys, thanks a lot for your plugin, it's awesome!

Just wanted to know if you have (or are considering to add) any way to indicate where I am about to put the new block (like a line showing where it would be placed if moved - a line on the bottom if it will be placed below the other block, or viceversa). Because I noticed that currently, when dragging a block it is not clear if it will be positioned on the top or the bottom of the other block. 

Thanks again!

**Comment by juanhurtado10** [comment]
Hey, @GFPdu really nice to hear from you!

We totally got you. By design, we decided to keep it without borders but you are right it is not clear enough. There is a workaround using CSS that may help you.

```
.ce-block--drop-target .ce-block__content {
  border: 1px dashed #aaa;
}
```

We are going to explore how to improve this! ... We will keep you posted :).

Best,
Juan

**Comment by GFPdu** [comment]
Hey @juanhurtado10! Thanks a lot for your quick answer. 

Yeah, in fact that would not work because I still have border on the whole block and I only want it to show where the future block would be positioned -if it's going to be in the top or in the bottom-. 

For example, if I want to position one block on the top of number two (or the bottom of number six), it would be something like: 
<img width="634" alt="Screenshot 2021-02-25 at 21 56 19" src="https://user-images.githubusercontent.com/32202381/109216239-8ee31f00-77b4-11eb-9c72-bbed9c261953.png"> 

Thanks again for your help!

**Comment by MakarovCode** [comment]
Hey guys, first this plugin is very useful. 
I did some tweaking to the css and the dragstart and drop listeners to make the drag n drop smoother

**index.css**

```css
.ce-block--drop-target .ce-block__content{
  border-top: 3px solid #ff6ab4;
}

.ce-block--drop-target:last-child .ce-block__content{
  border-top: none;
  border-bottom: 3px solid #ff6ab4;
}
.ce-block--drop-target:first-child .ce-block__content{
  border-top: 3px solid #ff6ab4;
  border-bottom: none;
}

.ce-block--drop-target .ce-block__content:before {
  content: "";
  position: absolute;
  top: 50%;
  left: -20px;
  margin-top: -1px;
  height: 8px;
  width: 8px;
  border: solid #a0a0a0;
  border-width: 1px 1px 0 0;
  -webkit-transform-origin: right;
  transform-origin: right;
  -webkit-transform: rotate(45deg);
  transform: rotate(45deg);
}

.ce-block--drop-target .ce-block__content:after {
  background: none;
}
```

```javascript
setDragListener() {
    if (!this.readOnly) {
      const settingsButton = this.holder.querySelector('.ce-toolbar__settings-btn');

      settingsButton.setAttribute('draggable', 'true');
      settingsButton.addEventListener('dragstart', (event) => {
        this.startBlock = this.api.getCurrentBlockIndex();

        this.movingBlock = document.getElementsByClassName("ce-block--focused")[0];
        // Outline the moving block
        this.movingBlock.firstElementChild.style.outlineColor = "rgba(255, 106, 180, 0.8)"
        this.movingBlock.firstElementChild.style.outlineStyle = "dashed"
        this.movingBlock.firstElementChild.style.outlineWidth = "3px"
        
        // Set the drag image "ghost" to the block that is being dragged.
        event.dataTransfer.setDragImage(this.movingBlock.firstElementChild, this.movingBlock.firstElementChild.offsetWidth, 16);


      });
    }
  }
```

**setDropListener()**

```javascript
setDropListener() {
    document.addEventListener('drop', (event) => {
      // clears the outline for the moving block
      this.movingBlock.firstElementChild.style.outlineColor = null;
      this.movingBlock.firstElementChild.style.outlineStyle = null;
      this.movingBlock.firstElementChild.style.outlineWidth = null;
      const { target } = event;
      if (this.holder.contains(target)) {
        const dropTarget = this.getDropTarget(target);
        if (dropTarget) {
          this.endBlock = this.getTargetPosition(dropTarget);
          this.moveBlocks();
        }
      }
    });
  }
```
